DROP TABLE IF EXISTS breeds;

CREATE TABLE breeds (
    id SERIAL PRIMARY KEY,
    breed VARCHAR(255),
    count int
);

INSERT INTO breeds (breed, count) VALUES ('Affenpinscher', 0);
INSERT INTO breeds (breed, count) VALUES ('Afghan Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Africanis', 0);
INSERT INTO breeds (breed, count) VALUES ('Aidi', 0);
INSERT INTO breeds (breed, count) VALUES ('Airedale Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Akbash', 0);
INSERT INTO breeds (breed, count) VALUES ('Akita', 0);
INSERT INTO breeds (breed, count) VALUES ('Aksaray Malaklisi', 0);
INSERT INTO breeds (breed, count) VALUES ('Alano Español', 0);
INSERT INTO breeds (breed, count) VALUES ('Alapaha Blue Blood Bulldog', 0);
INSERT INTO breeds (breed, count) VALUES ('Alaskan Husky', 0);
INSERT INTO breeds (breed, count) VALUES ('Alaskan Klee Kai', 0);
INSERT INTO breeds (breed, count) VALUES ('Alaskan Malamute', 0);
INSERT INTO breeds (breed, count) VALUES ('Alopekis', 0);
INSERT INTO breeds (breed, count) VALUES ('Alpine Dachsbracke', 0);
INSERT INTO breeds (breed, count) VALUES ('American Bulldog', 0);
INSERT INTO breeds (breed, count) VALUES ('American Bully', 0);
INSERT INTO breeds (breed, count) VALUES ('American Cocker Spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('American English Coonhound', 0);
INSERT INTO breeds (breed, count) VALUES ('American Eskimo Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('American Foxhound', 0);
INSERT INTO breeds (breed, count) VALUES ('American Hairless Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('American Leopard Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('American Pit Bull Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('American Staffordshire Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('American Water Spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('Andalusian Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Anglo-Français de Petite Vénerie', 0);
INSERT INTO breeds (breed, count) VALUES ('Appenzeller Sennenhund', 0);
INSERT INTO breeds (breed, count) VALUES ('Ariège Pointer', 0);
INSERT INTO breeds (breed, count) VALUES ('Ariégeois', 0);
INSERT INTO breeds (breed, count) VALUES ('Argentine Pila', 0);
INSERT INTO breeds (breed, count) VALUES ('Armant', 0);
INSERT INTO breeds (breed, count) VALUES ('Armenian Gampr', 0);
INSERT INTO breeds (breed, count) VALUES ('Artois Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Australian Cattle Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Australian Kelpie', 0);
INSERT INTO breeds (breed, count) VALUES ('Australian Shepherd', 0);
INSERT INTO breeds (breed, count) VALUES ('Australian Silky Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Australian Stumpy Tail Cattle Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Australian Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Austrian Black and Tan Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Austrian Pinscher', 0);
INSERT INTO breeds (breed, count) VALUES ('Azawakh', 0);
INSERT INTO breeds (breed, count) VALUES ('Bắc Hà dog|Bắc Hà', 0);
INSERT INTO breeds (breed, count) VALUES ('Bakharwal dog|Bakharwal', 0);
INSERT INTO breeds (breed, count) VALUES ('Banjara Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Bankhar Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Barak hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Barbado da Terceira', 0);
INSERT INTO breeds (breed, count) VALUES ('Barbet', 0);
INSERT INTO breeds (breed, count) VALUES ('Basenji', 0);
INSERT INTO breeds (breed, count) VALUES ('Basque Shepherd Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Basset Artésien Normand', 0);
INSERT INTO breeds (breed, count) VALUES ('Basset Bleu de Gascogne', 0);
INSERT INTO breeds (breed, count) VALUES ('Basset Fauve de Bretagne', 0);
INSERT INTO breeds (breed, count) VALUES ('Basset Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Bavarian Mountain Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Beagle', 0);
INSERT INTO breeds (breed, count) VALUES ('Beagle-Harrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Bearded Collie', 0);
INSERT INTO breeds (breed, count) VALUES ('Beauceron', 0);
INSERT INTO breeds (breed, count) VALUES ('Bedlington Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Belgian Shepherd', 0);
INSERT INTO breeds (breed, count) VALUES ('Bergamasco Shepherd', 0);
INSERT INTO breeds (breed, count) VALUES ('Berger Picard', 0);
INSERT INTO breeds (breed, count) VALUES ('Bernese Mountain Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Bichon Frisé', 0);
INSERT INTO breeds (breed, count) VALUES ('Biewer Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Billy', 0);
INSERT INTO breeds (breed, count) VALUES ('Black and Tan Coonhound', 0);
INSERT INTO breeds (breed, count) VALUES ('Black Norwegian Elkhound', 0);
INSERT INTO breeds (breed, count) VALUES ('Black Russian Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Black Mouth Cur', 0);
INSERT INTO breeds (breed, count) VALUES ('Bloodhound', 0);
INSERT INTO breeds (breed, count) VALUES ('Blue Lacy', 0);
INSERT INTO breeds (breed, count) VALUES ('Blue Picardy Spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('Bluetick Coonhound', 0);
INSERT INTO breeds (breed, count) VALUES ('Boerboel', 0);
INSERT INTO breeds (breed, count) VALUES ('Bohemian Shepherd', 0);
INSERT INTO breeds (breed, count) VALUES ('Bolognese dog|Bolognese', 0);
INSERT INTO breeds (breed, count) VALUES ('Border Collie', 0);
INSERT INTO breeds (breed, count) VALUES ('Border Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Borzoi', 0);
INSERT INTO breeds (breed, count) VALUES ('Boston Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Bouvier des Ardennes', 0);
INSERT INTO breeds (breed, count) VALUES ('Bouvier des Flandres', 0);
INSERT INTO breeds (breed, count) VALUES ('Boxer', 0);
INSERT INTO breeds (breed, count) VALUES ('Boykin Spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('Bracco Italiano', 0);
INSERT INTO breeds (breed, count) VALUES ('Braque dAuvergne', 0);
INSERT INTO breeds (breed, count) VALUES ('Braque du Bourbonnais', 0);
INSERT INTO breeds (breed, count) VALUES ('Braque Français', 0);
INSERT INTO breeds (breed, count) VALUES ('Braque Saint-Germain', 0);
INSERT INTO breeds (breed, count) VALUES ('Brazilian Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Briard', 0);
INSERT INTO breeds (breed, count) VALUES ('Briquet de Provence', 0);
INSERT INTO breeds (breed, count) VALUES ('Briquet Griffon Vendéen', 0);
INSERT INTO breeds (breed, count) VALUES ('Brittany', 0);
INSERT INTO breeds (breed, count) VALUES ('Broholmer', 0);
INSERT INTO breeds (breed, count) VALUES ('Bruno Jura Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Bucovina Shepherd Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Bulgarian Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Bulgarian Scenthound', 0);
INSERT INTO breeds (breed, count) VALUES ('Bull Arab', 0);
INSERT INTO breeds (breed, count) VALUES ('Bull Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Bulldog', 0);
INSERT INTO breeds (breed, count) VALUES ('Bullmastiff', 0);
INSERT INTO breeds (breed, count) VALUES ('Bully Kutta', 0);
INSERT INTO breeds (breed, count) VALUES ('Burgos Pointer', 0);
INSERT INTO breeds (breed, count) VALUES ('Ca Mè Mallorquí', 0);
INSERT INTO breeds (breed, count) VALUES ('Ca de Bou', 0);
INSERT INTO breeds (breed, count) VALUES ('Ca Rater Mallorquí', 0);
INSERT INTO breeds (breed, count) VALUES ('Cairn Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Calupoh', 0);
INSERT INTO breeds (breed, count) VALUES ('Campeiro Bulldog', 0);
INSERT INTO breeds (breed, count) VALUES ('Can de Chira', 0);
INSERT INTO breeds (breed, count) VALUES ('Can de Palleiro', 0);
INSERT INTO breeds (breed, count) VALUES ('Canaan Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Canadian Eskimo Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Cane Corso', 0);
INSERT INTO breeds (breed, count) VALUES ('Cane di Oropa', 0);
INSERT INTO breeds (breed, count) VALUES ('Cane Paratore', 0);
INSERT INTO breeds (breed, count) VALUES ('Cantabrian Water Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Cão de Gado Transmontano', 0);
INSERT INTO breeds (breed, count) VALUES ('Cardigan Welsh Corgi', 0);
INSERT INTO breeds (breed, count) VALUES ('Carea Leonés', 0);
INSERT INTO breeds (breed, count) VALUES ('Carolina Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Carpathian Shepherd Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Castro Laboreiro Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Catahoula Leopard Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Catalan Sheepdog', 0);
INSERT INTO breeds (breed, count) VALUES ('Caucasian Shepherd Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Cavalier King Charles Spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('Central Asian Shepherd Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Český fousek', 0);
INSERT INTO breeds (breed, count) VALUES ('Český strakatý pes', 0);
INSERT INTO breeds (breed, count) VALUES ('Cesky Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Chesapeake Bay Retriever', 0);
INSERT INTO breeds (breed, count) VALUES ('Chien Français Blanc et Noir', 0);
INSERT INTO breeds (breed, count) VALUES ('Chien Français Blanc et Orange', 0);
INSERT INTO breeds (breed, count) VALUES ('Chien Français Tricolore', 0);
INSERT INTO breeds (breed, count) VALUES ('Chihuahua', 0);
INSERT INTO breeds (breed, count) VALUES ('Chilean Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Chinese Crested Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Chinook', 0);
INSERT INTO breeds (breed, count) VALUES ('Chippiparai', 0);
INSERT INTO breeds (breed, count) VALUES ('Chongqing dog|Chongqing', 0);
INSERT INTO breeds (breed, count) VALUES ('Chortai', 0);
INSERT INTO breeds (breed, count) VALUES ('Chow Chow', 0);
INSERT INTO breeds (breed, count) VALUES ('Chukotka sled dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Cimarrón Uruguayo', 0);
INSERT INTO breeds (breed, count) VALUES ('Cirneco dellEtna', 0);
INSERT INTO breeds (breed, count) VALUES ('Clumber Spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('Colombian Fino Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Continental bulldog', 0);
INSERT INTO breeds (breed, count) VALUES ('Corsican Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Coton de Tulear', 0);
INSERT INTO breeds (breed, count) VALUES ('Cretan Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Croatian Sheepdog', 0);
INSERT INTO breeds (breed, count) VALUES ('Curly-coated Retriever', 0);
INSERT INTO breeds (breed, count) VALUES ('Czechoslovakian Wolfdog', 0);
INSERT INTO breeds (breed, count) VALUES ('Dachshund', 0);
INSERT INTO breeds (breed, count) VALUES ('Dalmatian', 0);
INSERT INTO breeds (breed, count) VALUES ('Dandie Dinmont Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Danish Spitz', 0);
INSERT INTO breeds (breed, count) VALUES ('Danish–Swedish Farmdog', 0);
INSERT INTO breeds (breed, count) VALUES ('Denmark Feist', 0);
INSERT INTO breeds (breed, count) VALUES ('Dikkulak', 0);
INSERT INTO breeds (breed, count) VALUES ('Dingo', 0);
INSERT INTO breeds (breed, count) VALUES ('Dobermann', 0);
INSERT INTO breeds (breed, count) VALUES ('Dogo Argentino', 0);
INSERT INTO breeds (breed, count) VALUES ('Dogo Sardesco', 0);
INSERT INTO breeds (breed, count) VALUES ('Dogue Brasileiro', 0);
INSERT INTO breeds (breed, count) VALUES ('Dogue de Bordeaux', 0);
INSERT INTO breeds (breed, count) VALUES ('Donggyeongi', 0);
INSERT INTO breeds (breed, count) VALUES ('Drentse Patrijshond', 0);
INSERT INTO breeds (breed, count) VALUES ('Drever', 0);
INSERT INTO breeds (breed, count) VALUES ('Dunker', 0);
INSERT INTO breeds (breed, count) VALUES ('Dutch Shepherd', 0);
INSERT INTO breeds (breed, count) VALUES ('Dutch Smoushond', 0);
INSERT INTO breeds (breed, count) VALUES ('East Siberian Laika', 0);
INSERT INTO breeds (breed, count) VALUES ('East European Shepherd', 0);
INSERT INTO breeds (breed, count) VALUES ('Ecuadorian Hairless Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('English Cocker Spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('English Foxhound', 0);
INSERT INTO breeds (breed, count) VALUES ('English Mastiff', 0);
INSERT INTO breeds (breed, count) VALUES ('English Setter', 0);
INSERT INTO breeds (breed, count) VALUES ('English Shepherd', 0);
INSERT INTO breeds (breed, count) VALUES ('English Springer Spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('English Toy Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Entlebucher Mountain Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Erbi Txakur', 0);
INSERT INTO breeds (breed, count) VALUES ('Estonian Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Estrela Mountain Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Eurasier', 0);
INSERT INTO breeds (breed, count) VALUES ('Faroese Sheepdog', 0);
INSERT INTO breeds (breed, count) VALUES ('Field Spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('Fila Brasileiro', 0);
INSERT INTO breeds (breed, count) VALUES ('Finnish Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Finnish Lapphund', 0);
INSERT INTO breeds (breed, count) VALUES ('Finnish Spitz', 0);
INSERT INTO breeds (breed, count) VALUES ('Flat-coated Retriever', 0);
INSERT INTO breeds (breed, count) VALUES ('Black Mouth Cur#Florida counterpart|Florida Brown Dog a/k/a Florida Cracker Cur', 0);
INSERT INTO breeds (breed, count) VALUES ('French Bulldog', 0);
INSERT INTO breeds (breed, count) VALUES ('French Spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('Galgo Español', 0);
INSERT INTO breeds (breed, count) VALUES ('Gascon Saintongeois', 0);
INSERT INTO breeds (breed, count) VALUES ('Gaucho sheepdog', 0);
INSERT INTO breeds (breed, count) VALUES ('Georgian Shepherd', 0);
INSERT INTO breeds (breed, count) VALUES ('German Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('German Longhaired Pointer', 0);
INSERT INTO breeds (breed, count) VALUES ('German Pinscher', 0);
INSERT INTO breeds (breed, count) VALUES ('German Roughhaired Pointer', 0);
INSERT INTO breeds (breed, count) VALUES ('German Shepherd', 0);
INSERT INTO breeds (breed, count) VALUES ('German Shorthaired Pointer', 0);
INSERT INTO breeds (breed, count) VALUES ('German Spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('German Spitz', 0);
INSERT INTO breeds (breed, count) VALUES ('German Wirehaired Pointer', 0);
INSERT INTO breeds (breed, count) VALUES ('Giant Schnauzer', 0);
INSERT INTO breeds (breed, count) VALUES ('Glen of Imaal Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Golden Retriever', 0);
INSERT INTO breeds (breed, count) VALUES ('Gończy Polski', 0);
INSERT INTO breeds (breed, count) VALUES ('Gordon Setter', 0);
INSERT INTO breeds (breed, count) VALUES ('Grand Anglo-Français Blanc et Noir', 0);
INSERT INTO breeds (breed, count) VALUES ('Grand Anglo-Français Blanc et Orange', 0);
INSERT INTO breeds (breed, count) VALUES ('Grand Anglo-Français Tricolore', 0);
INSERT INTO breeds (breed, count) VALUES ('Grand Basset Griffon Vendéen', 0);
INSERT INTO breeds (breed, count) VALUES ('Grand Bleu de Gascogne', 0);
INSERT INTO breeds (breed, count) VALUES ('Grand Griffon Vendéen', 0);
INSERT INTO breeds (breed, count) VALUES ('Great Dane', 0);
INSERT INTO breeds (breed, count) VALUES ('Greater Swiss Mountain Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Greek Harehound', 0);
INSERT INTO breeds (breed, count) VALUES ('Greek Shepherd', 0);
INSERT INTO breeds (breed, count) VALUES ('Greenland Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Greyhound', 0);
INSERT INTO breeds (breed, count) VALUES ('Griffon Bleu de Gascogne', 0);
INSERT INTO breeds (breed, count) VALUES ('Griffon Bruxellois', 0);
INSERT INTO breeds (breed, count) VALUES ('Griffon Fauve de Bretagne', 0);
INSERT INTO breeds (breed, count) VALUES ('Griffon Nivernais', 0);
INSERT INTO breeds (breed, count) VALUES ('Gull Dong', 0);
INSERT INTO breeds (breed, count) VALUES ('Gull Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Hällefors Elkhound', 0);
INSERT INTO breeds (breed, count) VALUES ('Halden Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Hamiltonstövare', 0);
INSERT INTO breeds (breed, count) VALUES ('Hanover Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Harrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Havanese dog|Havanese', 0);
INSERT INTO breeds (breed, count) VALUES ('Himalayan Sheepdog', 0);
INSERT INTO breeds (breed, count) VALUES ('Hmong bobtail dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Hokkaido', 0);
INSERT INTO breeds (breed, count) VALUES ('Hovawart', 0);
INSERT INTO breeds (breed, count) VALUES ('Huntaway', 0);
INSERT INTO breeds (breed, count) VALUES ('Hygen Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Ibizan Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Icelandic Sheepdog', 0);
INSERT INTO breeds (breed, count) VALUES ('Indian pariah dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Indian Spitz', 0);
INSERT INTO breeds (breed, count) VALUES ('Irish Red and White Setter', 0);
INSERT INTO breeds (breed, count) VALUES ('Irish Setter', 0);
INSERT INTO breeds (breed, count) VALUES ('Irish Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Irish Water Spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('Irish Wolfhound', 0);
INSERT INTO breeds (breed, count) VALUES ('Istrian Coarse-haired Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Istrian Shorthaired Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Italian Greyhound', 0);
INSERT INTO breeds (breed, count) VALUES ('Jack Russell Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Jagdterrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Jämthund', 0);
INSERT INTO breeds (breed, count) VALUES ('Japanese Chin', 0);
INSERT INTO breeds (breed, count) VALUES ('Japanese Spitz', 0);
INSERT INTO breeds (breed, count) VALUES ('Japanese Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Jeju dog|Jeju', 0);
INSERT INTO breeds (breed, count) VALUES ('Korean Jindo|Jindo', 0);
INSERT INTO breeds (breed, count) VALUES ('Jonangi', 0);
INSERT INTO breeds (breed, count) VALUES ('Kai Ken', 0);
INSERT INTO breeds (breed, count) VALUES ('Kaikadi', 0);
INSERT INTO breeds (breed, count) VALUES ('Kamchatka Sled Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Kangal Shepherd Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Kanni', 0);
INSERT INTO breeds (breed, count) VALUES ('Karakachan dog|Karakachan', 0);
INSERT INTO breeds (breed, count) VALUES ('Karelian Bear Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Karelo-Finnish Laika', 0);
INSERT INTO breeds (breed, count) VALUES ('Kars dog|Kars', 0);
INSERT INTO breeds (breed, count) VALUES ('Karst Shepherd', 0);
INSERT INTO breeds (breed, count) VALUES ('Kazakh Tazy', 0);
INSERT INTO breeds (breed, count) VALUES ('Keeshond', 0);
INSERT INTO breeds (breed, count) VALUES ('Kerry Beagle', 0);
INSERT INTO breeds (breed, count) VALUES ('Kerry Blue Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Khala', 0);
INSERT INTO breeds (breed, count) VALUES ('King Charles Spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('King Shepherd', 0);
INSERT INTO breeds (breed, count) VALUES ('Kintamani', 0);
INSERT INTO breeds (breed, count) VALUES ('Kishu', 0);
INSERT INTO breeds (breed, count) VALUES ('Kokoni', 0);
INSERT INTO breeds (breed, count) VALUES ('Kombai dog|Kombai', 0);
INSERT INTO breeds (breed, count) VALUES ('Komondor', 0);
INSERT INTO breeds (breed, count) VALUES ('Kooikerhondje', 0);
INSERT INTO breeds (breed, count) VALUES ('Koolie', 0);
INSERT INTO breeds (breed, count) VALUES ('Kromfohrländer', 0);
INSERT INTO breeds (breed, count) VALUES ('Kuchi dog|Kuchi', 0);
INSERT INTO breeds (breed, count) VALUES ('Kunming dog|Kunming', 0);
INSERT INTO breeds (breed, count) VALUES ('Kurdish Mastiff', 0);
INSERT INTO breeds (breed, count) VALUES ('Kuvasz', 0);
INSERT INTO breeds (breed, count) VALUES ('Labrador Retriever', 0);
INSERT INTO breeds (breed, count) VALUES ('Lagotto Romagnolo', 0);
INSERT INTO breeds (breed, count) VALUES ('Lài dog|Lài', 0);
INSERT INTO breeds (breed, count) VALUES ('Lakeland Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Lancashire Heeler', 0);
INSERT INTO breeds (breed, count) VALUES ('Landseer dog|Landseer', 0);
INSERT INTO breeds (breed, count) VALUES ('Lapponian Herder', 0);
INSERT INTO breeds (breed, count) VALUES ('Large Münsterländer', 0);
INSERT INTO breeds (breed, count) VALUES ('Leonberger', 0);
INSERT INTO breeds (breed, count) VALUES ('Levriero Sardo', 0);
INSERT INTO breeds (breed, count) VALUES ('Lhasa Apso', 0);
INSERT INTO breeds (breed, count) VALUES ('Liangshan Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Lithuanian Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Lobito Herreño', 0);
INSERT INTO breeds (breed, count) VALUES ('Löwchen', 0);
INSERT INTO breeds (breed, count) VALUES ('Lucas Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Lupo Italiano', 0);
INSERT INTO breeds (breed, count) VALUES ('Mackenzie River Husky', 0);
INSERT INTO breeds (breed, count) VALUES ('Magyar Agár', 0);
INSERT INTO breeds (breed, count) VALUES ('Mahratta Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Majorca Shepherd Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Maltese dog|Maltese', 0);
INSERT INTO breeds (breed, count) VALUES ('Manchester Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Maneto', 0);
INSERT INTO breeds (breed, count) VALUES ('Markiesje', 0);
INSERT INTO breeds (breed, count) VALUES ('Maremmano-Abruzzese Sheepdog', 0);
INSERT INTO breeds (breed, count) VALUES ('McNab dog|McNab', 0);
INSERT INTO breeds (breed, count) VALUES ('Miniature American Shepherd', 0);
INSERT INTO breeds (breed, count) VALUES ('Miniature Bull Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Miniature Fox Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Miniature Pinscher', 0);
INSERT INTO breeds (breed, count) VALUES ('Miniature Schnauzer', 0);
INSERT INTO breeds (breed, count) VALUES ('Molossus of Epirus', 0);
INSERT INTO breeds (breed, count) VALUES ('Mongrel', 0);
INSERT INTO breeds (breed, count) VALUES ('Montenegrin Mountain Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Moscow Watchdog', 0);
INSERT INTO breeds (breed, count) VALUES ('Mountain Cur', 0);
INSERT INTO breeds (breed, count) VALUES ('Mountain Feist', 0);
INSERT INTO breeds (breed, count) VALUES ('Mudhol Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Mudi', 0);
INSERT INTO breeds (breed, count) VALUES ('Neapolitan Mastiff', 0);
INSERT INTO breeds (breed, count) VALUES ('Nenets Herding Laika', 0);
INSERT INTO breeds (breed, count) VALUES ('New Guinea singing dog', 0);
INSERT INTO breeds (breed, count) VALUES ('New Zealand Heading Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Newfoundland dog|Newfoundland', 0);
INSERT INTO breeds (breed, count) VALUES ('Norfolk Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Norrbottenspets', 0);
INSERT INTO breeds (breed, count) VALUES ('Northern Inuit Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Norwegian Buhund', 0);
INSERT INTO breeds (breed, count) VALUES ('Norwegian Elkhound', 0);
INSERT INTO breeds (breed, count) VALUES ('Norwegian Lundehund', 0);
INSERT INTO breeds (breed, count) VALUES ('Norwich Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Nova Scotia Duck Tolling Retriever', 0);
INSERT INTO breeds (breed, count) VALUES ('Nureongi', 0);
INSERT INTO breeds (breed, count) VALUES ('Old Danish Pointer', 0);
INSERT INTO breeds (breed, count) VALUES ('Old English Sheepdog', 0);
INSERT INTO breeds (breed, count) VALUES ('Olde English Bulldogge', 0);
INSERT INTO breeds (breed, count) VALUES ('Otterhound', 0);
INSERT INTO breeds (breed, count) VALUES ('Pachón Navarro', 0);
INSERT INTO breeds (breed, count) VALUES ('Pampas Deerhound', 0);
INSERT INTO breeds (breed, count) VALUES ('Papillon dog|Papillon', 0);
INSERT INTO breeds (breed, count) VALUES ('Parson Russell Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Pastor Garafiano', 0);
INSERT INTO breeds (breed, count) VALUES ('Pastore della Lessinia e del Lagorai', 0);
INSERT INTO breeds (breed, count) VALUES ('Patagonian Sheepdog', 0);
INSERT INTO breeds (breed, count) VALUES ('Patterdale Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Pekingese', 0);
INSERT INTO breeds (breed, count) VALUES ('Pembroke Welsh Corgi', 0);
INSERT INTO breeds (breed, count) VALUES ('Perdigueiro Galego', 0);
INSERT INTO breeds (breed, count) VALUES ('Perro Majorero', 0);
INSERT INTO breeds (breed, count) VALUES ('Peruvian Hairless Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Petit Basset Griffon Vendéen', 0);
INSERT INTO breeds (breed, count) VALUES ('Petit Bleu de Gascogne', 0);
INSERT INTO breeds (breed, count) VALUES ('Phalène', 0);
INSERT INTO breeds (breed, count) VALUES ('Pharaoh Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Phu Quoc Ridgeback', 0);
INSERT INTO breeds (breed, count) VALUES ('Picardy Spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('Plummer Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Plott Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Podenco Andaluz', 0);
INSERT INTO breeds (breed, count) VALUES ('Podenco Canario', 0);
INSERT INTO breeds (breed, count) VALUES ('Podenco Valenciano', 0);
INSERT INTO breeds (breed, count) VALUES ('Pointer', 0);
INSERT INTO breeds (breed, count) VALUES ('Poitevin hound|Poitevin', 0);
INSERT INTO breeds (breed, count) VALUES ('Polish Greyhound', 0);
INSERT INTO breeds (breed, count) VALUES ('Polish Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Polish Lowland Sheepdog', 0);
INSERT INTO breeds (breed, count) VALUES ('Pomeranian dog|Pomeranian', 0);
INSERT INTO breeds (breed, count) VALUES ('Pont-Audemer Spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('Poodle', 0);
INSERT INTO breeds (breed, count) VALUES ('Porcelaine', 0);
INSERT INTO breeds (breed, count) VALUES ('Portuguese Podengo', 0);
INSERT INTO breeds (breed, count) VALUES ('Portuguese Pointer', 0);
INSERT INTO breeds (breed, count) VALUES ('Portuguese Sheepdog', 0);
INSERT INTO breeds (breed, count) VALUES ('Portuguese Water Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Posavac Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Pražský Krysařík', 0);
INSERT INTO breeds (breed, count) VALUES ('Presa Canario', 0);
INSERT INTO breeds (breed, count) VALUES ('Pudelpointer', 0);
INSERT INTO breeds (breed, count) VALUES ('Pug', 0);
INSERT INTO breeds (breed, count) VALUES ('Puli dog|Puli', 0);
INSERT INTO breeds (breed, count) VALUES ('Pumi dog|Pumi', 0);
INSERT INTO breeds (breed, count) VALUES ('Pungsan dog|Pungsan', 0);
INSERT INTO breeds (breed, count) VALUES ('Pyrenean Mastiff', 0);
INSERT INTO breeds (breed, count) VALUES ('Pyrenean Mountain Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Pyrenean Sheepdog', 0);
INSERT INTO breeds (breed, count) VALUES ('Rafeiro do Alentejo', 0);
INSERT INTO breeds (breed, count) VALUES ('Rajapalayam dog|Rajapalayam', 0);
INSERT INTO breeds (breed, count) VALUES ('Rampur Greyhound', 0);
INSERT INTO breeds (breed, count) VALUES ('Rastreador Brasileiro', 0);
INSERT INTO breeds (breed, count) VALUES ('Rat Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Ratonero Murciano', 0);
INSERT INTO breeds (breed, count) VALUES ('Redbone Coonhound', 0);
INSERT INTO breeds (breed, count) VALUES ('Rhodesian Ridgeback', 0);
INSERT INTO breeds (breed, count) VALUES ('Rize Koyun', 0);
INSERT INTO breeds (breed, count) VALUES ('Romanian Mioritic Shepherd Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Romanian Raven Shepherd Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Rottweiler', 0);
INSERT INTO breeds (breed, count) VALUES ('Rough Collie', 0);
INSERT INTO breeds (breed, count) VALUES ('Russian Spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('Russkiy Toy', 0);
INSERT INTO breeds (breed, count) VALUES ('Russo-European Laika', 0);
INSERT INTO breeds (breed, count) VALUES ('Ryukyu dog|Ryukyu', 0);
INSERT INTO breeds (breed, count) VALUES ('Saarloos wolfdog', 0);
INSERT INTO breeds (breed, count) VALUES ('Sabueso Español', 0);
INSERT INTO breeds (breed, count) VALUES ('Saint Miguel Cattle Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Saint-Usuge Spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('Sakhalin Husky', 0);
INSERT INTO breeds (breed, count) VALUES ('Saluki', 0);
INSERT INTO breeds (breed, count) VALUES ('Samoyed dog|Samoyed', 0);
INSERT INTO breeds (breed, count) VALUES ('Sapsali', 0);
INSERT INTO breeds (breed, count) VALUES ('Sarabi dog|Sarabi', 0);
INSERT INTO breeds (breed, count) VALUES ('Sardinian Shepherd Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Šarplaninac', 0);
INSERT INTO breeds (breed, count) VALUES ('Schapendoes', 0);
INSERT INTO breeds (breed, count) VALUES ('Schillerstövare', 0);
INSERT INTO breeds (breed, count) VALUES ('Schipperke', 0);
INSERT INTO breeds (breed, count) VALUES ('Schweizer Laufhund', 0);
INSERT INTO breeds (breed, count) VALUES ('Schweizerischer Niederlaufhund', 0);
INSERT INTO breeds (breed, count) VALUES ('Scottish Deerhound', 0);
INSERT INTO breeds (breed, count) VALUES ('Scottish Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Sealyham Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Segugio dellAppennino', 0);
INSERT INTO breeds (breed, count) VALUES ('Segugio Italiano', 0);
INSERT INTO breeds (breed, count) VALUES ('Segugio Maremmano', 0);
INSERT INTO breeds (breed, count) VALUES ('Serbian Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Serbian Tricolour Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Serrano Bulldog', 0);
INSERT INTO breeds (breed, count) VALUES ('Shar Pei', 0);
INSERT INTO breeds (breed, count) VALUES ('Shetland Sheepdog', 0);
INSERT INTO breeds (breed, count) VALUES ('Shiba Inu', 0);
INSERT INTO breeds (breed, count) VALUES ('Shih Tzu', 0);
INSERT INTO breeds (breed, count) VALUES ('Shikoku dog|Shikoku', 0);
INSERT INTO breeds (breed, count) VALUES ('Shiloh Shepherd', 0);
INSERT INTO breeds (breed, count) VALUES ('Siberian Husky', 0);
INSERT INTO breeds (breed, count) VALUES ('Silken Windhound', 0);
INSERT INTO breeds (breed, count) VALUES ('Sinhala Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Skye Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Sloughi', 0);
INSERT INTO breeds (breed, count) VALUES ('Slovak Rough-haired Pointer', 0);
INSERT INTO breeds (breed, count) VALUES ('Slovak Cuvac', 0);
INSERT INTO breeds (breed, count) VALUES ('Slovenský kopov', 0);
INSERT INTO breeds (breed, count) VALUES ('Smaland Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Small Međimurje Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Small Münsterländer', 0);
INSERT INTO breeds (breed, count) VALUES ('Smithfield', 0);
INSERT INTO breeds (breed, count) VALUES ('Smooth Collie', 0);
INSERT INTO breeds (breed, count) VALUES ('Smooth Fox Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Soft-coated Wheaten Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('South Russian Ovcharka', 0);
INSERT INTO breeds (breed, count) VALUES ('Spanish Mastiff', 0);
INSERT INTO breeds (breed, count) VALUES ('Spanish Water Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Spino degli Iblei', 0);
INSERT INTO breeds (breed, count) VALUES ('Spinone Italiano', 0);
INSERT INTO breeds (breed, count) VALUES ('Sporting Lucas Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('St. Bernard', 0);
INSERT INTO breeds (breed, count) VALUES ('St. Hubert Jura Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Stabyhoun', 0);
INSERT INTO breeds (breed, count) VALUES ('Staffordshire Bull Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Standard Schnauzer', 0);
INSERT INTO breeds (breed, count) VALUES ('Stephens Stock', 0);
INSERT INTO breeds (breed, count) VALUES ('Styrian Coarse-haired Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Sussex Spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('Swedish Lapphund', 0);
INSERT INTO breeds (breed, count) VALUES ('Swedish Vallhund', 0);
INSERT INTO breeds (breed, count) VALUES ('Taigan', 0);
INSERT INTO breeds (breed, count) VALUES ('Taiwan Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Tamaskan Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Tang Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Tarsus çatalburun', 0);
INSERT INTO breeds (breed, count) VALUES ('Tatra Shepherd Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Teddy Roosevelt Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Telomian', 0);
INSERT INTO breeds (breed, count) VALUES ('Tenterfield Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Thai Bangkaew Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Thai Ridgeback', 0);
INSERT INTO breeds (breed, count) VALUES ('Tibetan Kyi Apso', 0);
INSERT INTO breeds (breed, count) VALUES ('Tibetan Mastiff', 0);
INSERT INTO breeds (breed, count) VALUES ('Tibetan spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('Tibetan Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Tonya Finosu', 0);
INSERT INTO breeds (breed, count) VALUES ('Tornjak', 0);
INSERT INTO breeds (breed, count) VALUES ('Tosa', 0);
INSERT INTO breeds (breed, count) VALUES ('Toy Fox Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Toy Manchester Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Transylvanian Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Treeing Cur', 0);
INSERT INTO breeds (breed, count) VALUES ('Treeing Feist', 0);
INSERT INTO breeds (breed, count) VALUES ('Treeing Tennessee Brindle', 0);
INSERT INTO breeds (breed, count) VALUES ('Treeing Walker Coonhound', 0);
INSERT INTO breeds (breed, count) VALUES ('Trigg Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Tyrolean Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Valencian Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Vikhan', 0);
INSERT INTO breeds (breed, count) VALUES ('Villano de Las Encartaciones', 0);
INSERT INTO breeds (breed, count) VALUES ('Villanuco de Las Encartaciones', 0);
INSERT INTO breeds (breed, count) VALUES ('Vizsla', 0);
INSERT INTO breeds (breed, count) VALUES ('Volkosob', 0);
INSERT INTO breeds (breed, count) VALUES ('Volpino Italiano', 0);
INSERT INTO breeds (breed, count) VALUES ('Weimaraner', 0);
INSERT INTO breeds (breed, count) VALUES ('Welsh Hound', 0);
INSERT INTO breeds (breed, count) VALUES ('Welsh Sheepdog', 0);
INSERT INTO breeds (breed, count) VALUES ('Welsh Springer Spaniel', 0);
INSERT INTO breeds (breed, count) VALUES ('Welsh Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('West Country Harrier', 0);
INSERT INTO breeds (breed, count) VALUES ('West Highland White Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('West Siberian Laika', 0);
INSERT INTO breeds (breed, count) VALUES ('Westphalian Dachsbracke', 0);
INSERT INTO breeds (breed, count) VALUES ('Wetterhoun', 0);
INSERT INTO breeds (breed, count) VALUES ('Whippet', 0);
INSERT INTO breeds (breed, count) VALUES ('White Shepherd', 0);
INSERT INTO breeds (breed, count) VALUES ('White Swiss Shepherd Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Wire Fox Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Wirehaired Pointing Griffon', 0);
INSERT INTO breeds (breed, count) VALUES ('Wirehaired Vizsla', 0);
INSERT INTO breeds (breed, count) VALUES ('Xiasi Dog', 0);
INSERT INTO breeds (breed, count) VALUES ('Xoloitzcuintle', 0);
INSERT INTO breeds (breed, count) VALUES ('Yakutian Laika', 0);
INSERT INTO breeds (breed, count) VALUES ('Yorkshire Terrier', 0);
INSERT INTO breeds (breed, count) VALUES ('Zerdava', 0);
